# Generated by Django 2.0.2 on 2018-03-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
