# Generated by Django 2.0.2 on 2018-03-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0002_issues_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='description',
        ),
    ]
