# Generated by Django 2.0.2 on 2018-03-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0004_auto_20180323_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='bodySubLocation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='selector_status',
            field=models.TextField(default=''),
        ),
    ]
