# Generated by Django 2.0.2 on 2018-03-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0007_auto_20180323_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='bodySubLocation',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='selector_status',
        ),
    ]
