# Generated by Django 2.0.2 on 2018-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0008_auto_20180323_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='bodySubLocation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='selector_status',
            field=models.TextField(default=''),
        ),
    ]
