# Generated by Django 2.0.2 on 2018-03-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0011_symptomrelatedissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomrelatedissue',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='symptomrelatedissue',
            name='symptom',
        ),
        migrations.DeleteModel(
            name='SymptomRelatedIssue',
        ),
    ]
