# Generated by Django 2.0.2 on 2018-03-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0012_auto_20180325_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomRelatedIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('ranking', models.SmallIntegerField(default=0)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdoc.Issues')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdoc.Symptoms')),
            ],
        ),
    ]
