# Generated by Django 2.0.2 on 2018-03-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdoc', '0015_report_issue_ranks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='issue_ranks',
        ),
    ]
